### ISSUE TITLE
Adapt the template chart copied to the integration’s needs

### ISSUE THREAD

**Issue by kang-makes** [newrelic/k8s-metadata-injection#142]
In #141 we created and tested a pipeline that was able to deploy helm charts in this repository.

Now we have to adapt that helm chart to have all the features that it has the original [helm-repository](https://github.com/newrelic/helm-charts/tree/master/charts/nri-metadata-injection)

Please, take also care of any possible issue that could be open on the [helm-chart repository](https://github.com/newrelic/helm-charts/issues/). I had triaged them but some of them could have slipped to it.

You should take at least a glance at this issue/s:
 - newrelic/helm-charts#442
 - newrelic/helm-charts#302

---

- [x] Include and use common library
- [ ] Readme / docs updates

**Comment by sigilioso** [comment]
New common.library helper needed, see: [helm-charts#785](https://github.com/newrelic/helm-charts/pull/785)
