### ISSUE TITLE
[chart] Don't run as root

### ISSUE THREAD

**Issue by kang-makes** [newrelic/k8s-metadata-injection#175]
@invidian commented on [Tue Apr 20 2021](https://github.com/newrelic/helm-charts/issues/337)

**Is your feature request related to a problem? Please describe.**

Currently `nri-metadata-injection` Deployments runs as root, which is not really needed.

**Describe the solution you'd like**

`nri-metadata-injection` runs as non-root user.

**Additional context**

This might break thing if one runs it on different port. See https://github.com/newrelic/k8s-metadata-injection/issues/69 for more details.

**Comment by tgolly** [comment]
Just FYI, Microsoft Defender for Cloud picks this NewRelic pod up as "unhealthy" under the "Running containers as root user should be avoided" policy.  I assume other sec tools are picking this up as well.

It would be great if it could run with `runAsNonRoot: true` if possible.
