### ISSUE TITLE
Pod annotations should apply to batch job pods

### ISSUE THREAD

**Issue by jdfalk** [newrelic/k8s-metadata-injection#192]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

Currently the batch jobs do not have any fields for annotations on the pod. Istio looks for annotations on the pod to see if it should inject the istio proxy. In the case of a batch job it will inject the proxy but the pod will never complete as the proxy will stay running  indefinitely. This could be avoided if it either followed the global pod annotations or if it had its own field.

## Steps to Reproduce
Field missing in: 
[job-createSecret.yaml](https://github.com/newrelic/k8s-metadata-injection/blob/main/charts/nri-metadata-injection/templates/admission-webhooks/job-patch/job-createSecret.yaml)

## Expected Behavior
Field would be present or would follow the chart pod annotations field

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment
* N/A

## Additional context
Currently this prevents us from deploying the NRI-Metadata-Injection chart.  Istio's failures with batch jobs has been discussed extensively [here.](https://github.com/istio/istio/issues/6324)

**Comment by davidgit** [comment]
We appreciate you taking the time to bring this to our attention. After reviewing this issue, we are unable to commit on a timeline to resolution but we encourage community contributions and are happy to collaborate on design proposals and pull requests. 

Would you like to to propose a PR for thi? See our PR guidelines in the README.

**Comment by htroisi** [comment]
This was fixed in #261. Thanks for the contribution @janario!
