### ISSUE TITLE
PodSecurityPolicy v1beta1 has been deprecated since version 1.21 and is being deleted in version 1.25

### ISSUE THREAD

**Issue by meyerkev** [newrelic/k8s-metadata-injection#203]
## Description

PodSecurityPolicy has been deprecated since version 1.21 and is being deleted in version 1.25 which is the next quarterly release on [23 August 2022](https://www.kubernetes.dev/resources/release/#:~:text=The%201.25%20release%20cycle%20is,4%20%E2%80%94%20Production%20Readiness%20Soft%20Freeze)

## Steps to Reproduce

Install this Helm chart with --debug enabled and a warning will pop up in the debug output

`helm:cqmEq> W0812 01:40:52.489647   75341 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+`

## Expected Behavior

That is an interesting discussion that we have to figure out between now and 90 days from now.  (I know I don't have enough context, but I'd love to play fly on the wall).  

https://kubernetes.io/blog/2021/04/06/podsecuritypolicy-deprecation-past-present-and-future/ is the official k8s discussion around PSP's and the various options.  Either we can enable another Gatekeeper controller or we can use one of the built-in Pod Security Standards.

**Comment by davidgit** [comment]
We appreciate you taking the time to bring this to our attention. 

We plan to support v1.25 during the next quarter and we'll obviously tackle this deprecation. We'll keep you posted!

**Comment by arylatt** [comment]
Hi @davidgit, any updates on a roadmap for this update? Kubernetes 1.24 is EOL at the end of July this year.
