### ISSUE TITLE
k8s-metadata-injection pod is not able to start with hostNetwork=true when node port 8080 is used by another process

### ISSUE THREAD

**Issue by FilimonovEugene** [newrelic/k8s-metadata-injection#290]
## Description
Pod doesn't start because node port 8080 is already taken by another pod on that node, for instance AWS ALB Controller.

## Expected Behavior
Would be nice to have a possibility to configure k8s-metadata-injection health check port via Helm chart settings, instead of hardcoded 8080 port.

## Steps to Reproduce
1) Create a Kubernetes cluster with one node;
2) Deploy some service which uses 8080 port, with hostNetwork=true;
3) Deploy k8s-metadata-injection via nri-bundle Helm chart, with hostNetwork=true.

## Your Environment
AWS EKS cluster with Calico CNI.

**Comment by htijas** [comment]
Is this going to be worked upon? I would like to see this get implemented.
