### ISSUE TITLE
performance issues when the nri-metadata-injection app is enabled

### ISSUE THREAD

**Issue by davidbrota** [newrelic/k8s-metadata-injection#69]
## Description

Some GKE clusters were demonstrating significant delays in scheduling with the kubernetes integration bundle deployed via helm. When they disabled the metadata injection, the performance issues were resolved.

## Steps to Reproduce

Could not be reproduced

## Expected Behavior

The cluster shouldn't suffer performance issues when deploying the K8S integration and the metadata injection pod is running.

## Your Environment

It seems to happen on GKE clusters.

**Comment by smeeklai** [comment]
I also got a similar issue. My cluster is also on GKE but **a private cluster**. Suddenly new pods cannot get created.

I contacted GCP support team and they pointed me to this issue and guided me how to solve it. In summary, the `nri-metadata-injection` is using MutatingWebhook, in which `nri-metadata-injection` sends requests to the API server (master) and wait for responses. So if you happen to have a private cluster just like me, you have to create a firewall rule to allow access to the `nri-metadata-injection` container port, which is `8443` in this case.

Here's an [example](https://linkerd.io/2/reference/cluster-configuration/) from linkerd2 project on how to create a firewall rule for GKE.

**Comment by astrozyk** [comment]
I had the exact same issue in GKE as well because of having a private cluster. After contacting New Relic support they pointed me to this issue and the linkerd2 documentation that @smeeklai posted above was very helpful in us retrieving the exact information we needed quickly to get this working.

**Comment by invidian** [comment]
>I contacted GCP support team and they pointed me to this issue and guided me how to solve it. In summary, the nri-metadata-injection is using MutatingWebhook, in which nri-metadata-injection sends requests to the API server (master) and wait for responses. So if you happen to have a private cluster just like me, you have to create a firewall rule to allow access to the nri-metadata-injection container port from the API server. The port is 8443 in this case.

IIIRC GKE allows traffic for [port 443](https://cloud.google.com/kubernetes-engine/docs/how-to/private-clusters). I wonder if configuring the webhook to listen on this port (with extra capability) would help here. Perhaps it's more convenient to grant the capability to pod than to modify the firewall rules.

**Comment by davidgit** [comment]
This issue was closed because it has been inactive for a long time despite it can be reopened at any point if you think it still relevant.

Thank you for your contribution!
