### ISSUE TITLE
Move k8s metadata injection Job and travis tests

### ISSUE THREAD

**Issue by paologallinaharbur** [newrelic/k8s-metadata-injection#70]
https://fsi-build.pdx.vm.datanerd.us/view/k8s-metadata/job/k8s-metadata-injection-release/

Notice that:
 - The release in the job options directly in jenkins
 - The tests are performed in a minikube spin up in travis

We should make sure we follow a common pattern:
PR/Merge -> Run tests/build using a makefile
Create Tag -> Push release

**Comment by roobre** [comment]
Development of the release action is ready for first review on my local fork:
https://github.com/newrelic/k8s-metadata-injection/compare/main...roobre:santalla/gh-actions
