### ISSUE TITLE
[CI/CD] pre-release fails due to version check

### ISSUE THREAD

**Issue by paologallinaharbur** [newrelic/k8s-metadata-injection#79]
When checking during the release if the version is the one included into the deploy yaml, in `pre` release the wrong image is checked.

This causes in pre-release the job to fail:

https://github.com/newrelic/k8s-metadata-injection/runs/1682146992?check_suite_focus=true

**Comment by roobre** [comment]
This is a side-effect of the CI check and the yaml version being manual.
An easy fix would be to separate the version check, and skip it on prerelease.

**Comment by roobre** [comment]
This should have been fixed now, the `-pre` suffix is stripped from the version check.
